const weather_precaution_messages = [
  {
    id: 1,
    weather_icon: "thunderstorm",
    weather_condition: "Thunderstorm",
    weather_message_first_line: "Don't go outside ",
    weather_message_second_line: "unless necessary! ",
  },
  {
    id: 2,
    weather_icon: "rainy",
    weather_condition: "Drizzle",
    weather_message_first_line: "Don't forget your ",
    weather_message_second_line: "umbrella today! ",
  },
  {
    id: 3,
    weather_icon: "rainy",
    weather_condition: "Rain",
    weather_message_first_line: "Don't forget your ",
    weather_message_second_line: "umbrella today! ",
  },
  {
    id: 4,
    weather_icon: "snow",
    weather_condition: "Snow",
    weather_message_first_line: "Today it's colder ",
    weather_message_second_line: "than usual days! ",
  },
  {
    id: 5,
    weather_icon: "sunny",
    weather_condition: "Clear",
    weather_message_first_line: "Today it's clear ",
    weather_message_second_line: "than usual days! ",
  },
  {
    id: 6,
    weather_icon: "cloud",
    weather_condition: "Clouds",
    weather_message_first_line: "Today it's cloudy ",
    weather_message_second_line: "than usual days! ",
  },
  {
    id: 7,
    weather_icon: "cloud",
    weather_condition: "Haze",
    weather_message_first_line: "Atmosphere is  ",
    weather_message_second_line: "quiet haze today! ",
  },
  {
    id: 7,
    weather_icon: "cloud",
    weather_condition: "Smoke",
    weather_message_first_line: "Atmosphere is  ",
    weather_message_second_line: "quiet smoky today! ",
  },
  {
    id: 8,
    weather_icon: "cloud",
    weather_condition: "Fog",
    weather_message_first_line: "Atmosphere is  ",
    weather_message_second_line: "quiet foggy today! ",
  },
  {
    id: 9,
    weather_icon: "cloud",
    weather_condition: "Mist",
    weather_message_first_line: "Atmosphere is  ",
    weather_message_second_line: "quiet misty today! ",
  },
  {
    id: 10,
    weather_icon: "cloud",
    weather_condition: "Dust",
    weather_message_first_line: "Atmosphere is  ",
    weather_message_second_line: "quiet dusty today! ",
  },
  {
    id: 11,
    weather_icon: "cloud",
    weather_condition: "Sand",
    weather_message_first_line: "Atmosphere is  ",
    weather_message_second_line: "quiet dusty today! ",
  },
  {
    id: 12,
    weather_icon: "cloud",
    weather_condition: "Ash",
    weather_message_first_line: "Atmosphere is  ",
    weather_message_second_line: "quiet ashy today! ",
  },
  {
    id: 13,
    weather_icon: "cloud",
    weather_condition: "Squall",
    weather_message_first_line: "Atmosphere is  ",
    weather_message_second_line: "quiet dusty today! ",
  },
  {
    id: 14,
    weather_icon: "cloud",
    weather_condition: "Tornado",
    weather_message_first_line: "Atmosphere is  ",
    weather_message_second_line: "more dusty today! ",
  },
];

export default weather_precaution_messages;
